// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20250420223518_aaa")]
    partial class aaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.ToTable("Invocations");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("LocalVariables");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvocationId");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("SimAttributes");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("SimClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "Object",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("6bcaef21-441d-4d61-a8c8-96c9ac3c9cd2"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "int",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("6410546b-ab34-4168-9d5e-c434400dcef2"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "string",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("51e7d7df-c95c-4e93-ad81-2d6371aaf7a8"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "float",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("465ea3e8-af4f-4f03-adf7-c8003c30a259"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "double",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("083aa66d-50d6-48ea-b0d2-17376e66c072"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "decimal",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("e05387be-86de-4edd-bb56-1624fb55439e"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "char",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("1a77b10e-c125-4f2f-808c-286546e2afba"),
                            BaseClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d"),
                            Name = "bool",
                            State = 2
                        });
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accesibility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReturnTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("ReturnTypeId");

                    b.ToTable("SimMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbe54e44-2ccd-4c0e-9379-d5ac3cc5f0b2"),
                            Accesibility = 2,
                            Name = "Equals",
                            Privacity = 0,
                            RelatedClassId = new Guid("450360bc-385d-4d28-8f4b-74fb804bd34d")
                        });
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Invocations")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RelatedMethod");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("LocalVariables")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.HasOne("Domain.Invocation", null)
                        .WithMany("Parameters")
                        .HasForeignKey("InvocationId");

                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Parameters")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Attributes")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RelatedClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.HasOne("Domain.SimClass", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Methods")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "ReturnType")
                        .WithMany()
                        .HasForeignKey("ReturnTypeId");

                    b.Navigation("RelatedClass");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Navigation("Invocations");

                    b.Navigation("LocalVariables");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
