// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20250421175914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.ToTable("Invocations");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("LocalVariables");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvocationId");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("SimAttributes");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("SimClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "Object",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("f2bdcb72-86b4-4546-9b98-94ee3e6f6862"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "int",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("0ea21daa-75d4-4072-ad0c-97cbf5e806bd"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "string",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("db3531f5-2430-4ef5-a07c-158e217c0d40"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "float",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("dc1f15a3-65b3-4f5b-a4bd-a19e51c95038"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "double",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("2f6e81fd-d9f3-4b3b-8495-18db97a180d8"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "decimal",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("b5467b9b-29be-4986-ac3f-b69c6116f0ff"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "char",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("3a7c1a39-708a-408d-b360-5ac1b9e77ef5"),
                            BaseClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            Name = "bool",
                            State = 2
                        });
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accesibility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReturTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("ReturTypeId");

                    b.ToTable("SimMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b48d1779-02c9-4048-999d-230d7e66b978"),
                            Accesibility = 2,
                            Name = "Equals",
                            Privacity = 0,
                            RelatedClassId = new Guid("504f38cd-996c-4845-a703-5a449050c775"),
                            ReturTypeId = new Guid("3a7c1a39-708a-408d-b360-5ac1b9e77ef5")
                        });
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Invocations")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedMethod");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("LocalVariables")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.HasOne("Domain.Invocation", null)
                        .WithMany("Parameters")
                        .HasForeignKey("InvocationId");

                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Parameters")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Attributes")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.HasOne("Domain.SimClass", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Methods")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "ReturnType")
                        .WithMany()
                        .HasForeignKey("ReturTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Navigation("Invocations");

                    b.Navigation("LocalVariables");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
