// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20250528152459_virtual-override")]
    partial class virtualoverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.ExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasFilter("[ReferenceId] IS NOT NULL");

                    b.HasIndex("RelatedMethodId");

                    b.ToTable("Invocations");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("LocalVariables");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111111"),
                            Index = 0,
                            Name = "obj",
                            RelatedMethodId = new Guid("55555555-1111-1111-1111-111111111111"),
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-1111-1111-111111111111"),
                            Index = 0,
                            Name = "objA",
                            RelatedMethodId = new Guid("55555555-2222-1111-1111-111111111111"),
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-3333-1111-1111-111111111111"),
                            Index = 1,
                            Name = "objB",
                            RelatedMethodId = new Guid("55555555-2222-1111-1111-111111111111"),
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-4444-1111-1111-111111111111"),
                            Index = 0,
                            Name = "objA",
                            RelatedMethodId = new Guid("55555555-7777-1111-1111-111111111111"),
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-5555-1111-1111-111111111111"),
                            Index = 1,
                            Name = "objB",
                            RelatedMethodId = new Guid("55555555-7777-1111-1111-111111111111"),
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Domain.ParameterSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SignatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SignatureId");

                    b.HasIndex("TypeId");

                    b.ToTable("ParameterSignatures");
                });

            modelBuilder.Entity("Domain.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid>("RelatedInvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("References", (string)null);

                    b.HasDiscriminator<string>("ReferenceType").HasValue("Reference");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RelatedInvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedInvocationId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("SimAttributes");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("SimClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Object",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "void",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("22223222-2222-2222-2222-222222222222"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "bool",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "byte",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "sbyte",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "char",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "decimal",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-5555-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "double",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-6666-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "float",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-7777-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "int",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-8888-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "uint",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-9999-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "nint",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "nuint",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-bbbb-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "long",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "ulong",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-dddd-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "short",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-eeee-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "ushort",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "string",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "delegate",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-3333-1111-1111-111111111111"),
                            BaseClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "dynamic",
                            State = 2
                        });
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accesibility")
                        .HasColumnType("int");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReturnTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("ReturnTypeId");

                    b.ToTable("SimMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-1111-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Equals",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("22223222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Equals",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("22223222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-3333-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "Finalize",
                            Privacity = 1,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-4444-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "GetHashCode",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("33333333-7777-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "GetType",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-6666-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "MemberwiseClone",
                            Privacity = 1,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-7777-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "ReferenceEquals",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("22223222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-8888-1111-1111-111111111111"),
                            Accesibility = 2,
                            IsOverride = false,
                            IsStatic = false,
                            IsVirtual = false,
                            Name = "ToString",
                            Privacity = 2,
                            RelatedClassId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ReturnTypeId = new Guid("44444444-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("SimClassSimClass", b =>
                {
                    b.Property<Guid>("ImplementsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SimClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImplementsId", "SimClassId");

                    b.HasIndex("SimClassId");

                    b.ToTable("SimClassImplements", (string)null);
                });

            modelBuilder.Entity("Domain.ReferenceAttribute", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.HasDiscriminator().HasValue("Attribute");
                });

            modelBuilder.Entity("Domain.ReferenceBase", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceBase_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("Base");
                });

            modelBuilder.Entity("Domain.ReferenceParameter", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceParameter_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("Parameter");
                });

            modelBuilder.Entity("Domain.ReferenceStatic", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceStatic_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("Static");
                });

            modelBuilder.Entity("Domain.ReferenceStaticAttribute", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceStaticAttribute_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("StaticAttribute");
                });

            modelBuilder.Entity("Domain.ReferenceThis", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceThis_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("This");
                });

            modelBuilder.Entity("Domain.ReferenceVariable", b =>
                {
                    b.HasBaseType("Domain.Reference");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ReferenceId");

                    b.ToTable("References", t =>
                        {
                            t.Property("ReferenceId")
                                .HasColumnName("ReferenceVariable_ReferenceId");
                        });

                    b.HasDiscriminator().HasValue("Variable");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.HasOne("Domain.Reference", "Reference")
                        .WithOne("RelatedInvocation")
                        .HasForeignKey("Domain.Invocation", "ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Invocations")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reference");

                    b.Navigation("RelatedMethod");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("LocalVariables")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Parameters")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.ParameterSignature", b =>
                {
                    b.HasOne("Domain.Signature", "Signature")
                        .WithMany("Parameters")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Signature");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Signature", b =>
                {
                    b.HasOne("Domain.Invocation", "RelatedInvocation")
                        .WithOne("Signature")
                        .HasForeignKey("Domain.Signature", "RelatedInvocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedInvocation");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Attributes")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.HasOne("Domain.SimClass", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Methods")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.SimClass", "ReturnType")
                        .WithMany()
                        .HasForeignKey("ReturnTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("SimClassSimClass", b =>
                {
                    b.HasOne("Domain.SimClass", null)
                        .WithMany()
                        .HasForeignKey("ImplementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.SimClass", null)
                        .WithMany()
                        .HasForeignKey("SimClassId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ReferenceAttribute", b =>
                {
                    b.HasOne("Domain.SimAttribute", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceBase", b =>
                {
                    b.HasOne("Domain.SimClass", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceParameter", b =>
                {
                    b.HasOne("Domain.Parameter", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceStatic", b =>
                {
                    b.HasOne("Domain.SimClass", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceStaticAttribute", b =>
                {
                    b.HasOne("Domain.SimAttribute", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceThis", b =>
                {
                    b.HasOne("Domain.SimClass", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.ReferenceVariable", b =>
                {
                    b.HasOne("Domain.LocalVariable", "Reference")
                        .WithMany()
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reference");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Reference", b =>
                {
                    b.Navigation("RelatedInvocation");
                });

            modelBuilder.Entity("Domain.Signature", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Navigation("Invocations");

                    b.Navigation("LocalVariables");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
