// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20250421155820_FixReturnTypeSeed")]
    partial class FixReturnTypeSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.ToTable("Invocations");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("LocalVariables");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvocationId");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("SimAttributes");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("SimClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "Object",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("ba2feee1-2f3d-4b90-af73-6d949b4ac453"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "int",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("6d0b9c8e-4cc7-472c-9835-c9ee7456317c"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "string",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("69944855-67ad-47dc-9950-6c653b9d29eb"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "float",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("1f1c058f-d16f-4026-ad14-cfaf5dacd162"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "double",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("dd58c2f0-4606-4fff-ad0b-0ea5b8808c08"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "decimal",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("ada0ea3d-1087-47db-a128-8015e0c966e6"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "char",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("ead16992-fbcd-44d6-a92c-db535c962582"),
                            BaseClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            Name = "bool",
                            State = 2
                        });
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accesibility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReturTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("ReturTypeId");

                    b.ToTable("SimMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2320cd7-26f5-4503-b319-1919459a21bf"),
                            Accesibility = 2,
                            Name = "Equals",
                            Privacity = 0,
                            RelatedClassId = new Guid("8ffcbe9b-8013-434c-b430-c910f791e602"),
                            ReturTypeId = new Guid("ead16992-fbcd-44d6-a92c-db535c962582")
                        });
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Invocations")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedMethod");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("LocalVariables")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.HasOne("Domain.Invocation", null)
                        .WithMany("Parameters")
                        .HasForeignKey("InvocationId");

                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Parameters")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Attributes")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.HasOne("Domain.SimClass", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Methods")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "ReturnType")
                        .WithMany()
                        .HasForeignKey("ReturTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Navigation("Invocations");

                    b.Navigation("LocalVariables");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
