// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    partial class SimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.ToTable("Invocations");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("LocalVariables");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvocationId");

                    b.HasIndex("RelatedMethodId");

                    b.HasIndex("TypeId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("TypeId");

                    b.ToTable("SimAttributes");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseClassId");

                    b.ToTable("SimClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "Object",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("2112163b-6700-4901-926a-438d34eab0d1"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "int",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("7036f7bf-dd57-4626-9520-fcc01965b645"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "string",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("24c8422d-17b6-490a-b10e-0eca9b1bcf03"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "float",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("68e07265-d232-4569-b6eb-34172c0a0f56"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "double",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("465cf4a9-137b-4517-951d-2e61e2f44676"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "decimal",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("5b57e7d7-44ac-40ba-9d27-4763e42f4cf4"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "char",
                            State = 2
                        },
                        new
                        {
                            Id = new Guid("b71b8f93-2d44-4a71-af57-35d3a756a02f"),
                            BaseClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            Name = "bool",
                            State = 2
                        });
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accesibility")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Privacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReturTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClassId");

                    b.HasIndex("ReturTypeId");

                    b.ToTable("SimMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb8e9d45-3f1f-446f-a4b5-1657cc3f209f"),
                            Accesibility = 2,
                            Name = "Equals",
                            Privacity = 0,
                            RelatedClassId = new Guid("6c7032af-930b-4f6a-b69b-f9649e46184b"),
                            ReturTypeId = new Guid("b71b8f93-2d44-4a71-af57-35d3a756a02f")
                        });
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Invocations")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedMethod");
                });

            modelBuilder.Entity("Domain.LocalVariable", b =>
                {
                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("LocalVariables")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Parameter", b =>
                {
                    b.HasOne("Domain.Invocation", null)
                        .WithMany("Parameters")
                        .HasForeignKey("InvocationId");

                    b.HasOne("Domain.SimMethod", "RelatedMethod")
                        .WithMany("Parameters")
                        .HasForeignKey("RelatedMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedMethod");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimAttribute", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Attributes")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.SimClass", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.HasOne("Domain.SimClass", "BaseClass")
                        .WithMany()
                        .HasForeignKey("BaseClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseClass");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.HasOne("Domain.SimClass", "RelatedClass")
                        .WithMany("Methods")
                        .HasForeignKey("RelatedClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SimClass", "ReturnType")
                        .WithMany()
                        .HasForeignKey("ReturTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedClass");

                    b.Navigation("ReturnType");
                });

            modelBuilder.Entity("Domain.Invocation", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.SimClass", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Domain.SimMethod", b =>
                {
                    b.Navigation("Invocations");

                    b.Navigation("LocalVariables");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
